version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "MockProjectVuongND9"
s3_bucket = "vuongnd9-bucket"
s3_prefix = "MockProject"
region = "ap-southeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
